

server:
  port: 9090

spring:
  application:
    name: Product Management
  datasource:
    url: jdbc:h2:mem:generate-prescription
    driver-class-name: org.h2.Driver
    username: root
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-db
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect


springdoc:
  swagger-ui:
    path: /swagger




