

server:
  port: 9090

spring:
  application:
    name: Generate prescription
  datasource:
    url: jdbc:h2:mem:generateprescription
    driver-class-name: org.h2.Driver
    username: root
    password: sa
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

frontend:
  domain: localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
    com.tareq23.prescription.config: DEBUG

third-party-api:
  rx-term:
    all-concept: https://rxnav.nlm.nih.gov/REST/RxTerms/allconcepts.json


token:
  signing:
    key: SECRET22k3j3k3j3k3j3k3j3k3j3k3j3k3j3k3j3k12KEYSECRET12KEYSECRET12KEYSECRET12KEYSECRET12KEYSECRET12KEY123456tareq23

springdoc:
  swagger-ui:
    path: /swagger




